---

- hosts: all

  tasks:

    # Variables from facts gathering such as "ansible_machine", "ansible_architecture" or "ansible_userspace_architecture" are wrong about "amd64" architecture, they state that this is an "x86_64"
    - name: Get architecture of target node
      shell: dpkg --print-architecture
      register: newborn_arch

    # ┌─────────────┐
    # │   GHOSTTY   │
    # └─────────────┘

    - name: Ghostty | Copy terminfo file
      copy:
        src: configs/ghostty.txt
        dest: /tmp/ghostty.txt
        owner: root
        group: root
        mode: '0755'

    - name: Ghostty | Apply terminfo
      shell: tic -x /tmp/ghostty.txt

    - name: Ghostty | Delete terminfo file
      file:
        path: /tmp/ghostty.txt
        state: absent

    # ┌─────────────┐
    # │   SCRIPTS   │
    # └─────────────┘

    - name: Scripts | Create directory
      file:
        path: /root/newborn
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Scripts | Copy scripts
      copy:
        src: "scripts/{{ item }}"
        dest: /root/newborn/{{ item }}
        owner: root
        group: root
        mode: '0755'
      loop:
        - iptables.sh
        - swap.sh

    # ┌────────────────┐
    # │   SOME SETUP   │
    # └────────────────┘

    - name: Setup | Resize filesystem
      shell: |
        DISK_LABEL=$(df | grep -E '\/$' | awk '{print $1}')
        resize2fs $DISK_LABEL
        df -h | grep $DISK_LABEL
        unset DISK_LABEL

    - name: Setup | Set swap
      shell: "/root/newborn/swap.sh {{ newborn_swap }}"

    - name: Setup | Create disk reserve file
      command: fallocate -l 2G /disk-space-reserve
      when: newborn_reserve_file == "y"

    - name: Setup | Set UTC timezone
      shell: |
        ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
        dpkg-reconfigure --frontend noninteractive tzdata
      register: result_setup_timezone
      retries: 10
      delay: 30
      until: result_setup_timezone is not failed

    - name: Setup | Update system
      apt:
        update_cache: true
        upgrade: dist
        autoremove: true
        lock_timeout: 600
      register: result_setup_apt_upgrade
      retries: 10
      delay: 10
      until: result_setup_apt_upgrade is not failed

    - name: Setup | Install packages
      apt:
        name:
          - curl
          - python3
          - vim
          - iptables
          - iptables-persistent
          - cron
          - locales
          - build-essential
        update_cache: true
        lock_timeout: 600
      register: result_setup_apt_install
      retries: 10
      delay: 10
      until: result_setup_apt_install is not failed

    - name: Setup | Install Rust & Cargo
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable --no-modify-path
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

    - name: Setup | Install Rust packages
      shell: |
        mkdir -p /opt/rust-utils
        /root/.cargo/bin/cargo binstall --only-signed --disable-telemetry --install-path /opt/rust-utils -y bat bottom du-dust eza fd-find ripgrep

    - name: Setup | Uninstall Rust & Cargo
      shell: |
        /root/.cargo/bin/rustup self uninstall -y

    - name: Setup | Set password for root
      user:
        name: root
        password: "{{ newborn_password | password_hash('sha512', newborn_password_salt) }}"

    - name: Setup | Set hostname
      hostname:
        name: "{{ newborn_hostname }}"
        use: systemd

    - name: Setup | Add hostname to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }} {{ newborn_hostname }}"
      loop:
        - 127.0.0.1
        - ::1

    - name: Setup | Generate UTF-8 locale
      community.general.locale_gen:
        name: en_US.UTF-8
        state: present

    - name: Setup | Set default locale
      lineinfile:
        path: /etc/default/locale
        regexp: '^LANG='
        line: 'LANG=en_US.UTF-8'

    - name: Setup | Ensure LC_ALL is set
      lineinfile:
        path: /etc/default/locale
        regexp: '^LC_ALL='
        line: 'LC_ALL=en_US.UTF-8'

    # ┌──────────────┐
    # │   FIREWALL   │
    # └──────────────┘

    - name: Firewall | Disable ufw
      shell: /root/newborn/iptables.sh remove_ufw

    - name: Firewall | Update script
      blockinfile:
        path: /root/newborn/iptables.sh
        block: |
          {% filter indent(width=4, first=true) %}
          # Allow access to ports 80 and 443 from Cloudflare
          CF_IP_RANGES_V4=$(curl -Ls https://www.cloudflare.com/ips-v4)
          for ip in ${CF_IP_RANGES_V4}
          do
              iptables -A $CHAIN -p tcp -s $ip --dport 80  -m comment --comment 'Cloudflare' -j RETURN
              iptables -A $CHAIN -p tcp -s $ip --dport 443 -m comment --comment 'Cloudflare' -j RETURN
          done
          CF_IP_RANGES_V6=$(curl -Ls https://www.cloudflare.com/ips-v6)
          for ip in ${CF_IP_RANGES_V6}
          do
              ip6tables -A $CHAIN -p tcp -s $ip --dport 80  -m comment --comment 'Cloudflare' -j RETURN
              ip6tables -A $CHAIN -p tcp -s $ip --dport 443 -m comment --comment 'Cloudflare' -j RETURN
          done
          {% endfilter %}
        marker: "    # {mark} ANSIBLE MANAGED BLOCK : HTTP"
        state: present
      when: newborn_firewall_http == 'cloudflare'

    - name: Firewall | Update script
      blockinfile:
        path: /root/newborn/iptables.sh
        block: |
          {% filter indent(width=4, first=true) %}
          # Allow access to ports 80 and 443
          call_iptables -A $CHAIN -p tcp --dport 80 -j ACCEPT
          call_iptables -A $CHAIN -p tcp --dport 443 -j ACCEPT
          {% endfilter %}
        marker: "    # {mark} ANSIBLE MANAGED BLOCK : HTTP"
        state: present
      when: newborn_firewall_http == 'anywhere'

    - name: Firewall | Execute the script
      shell: /root/newborn/iptables.sh

    - name: Firewall | Create a cron job to apply rules
      cron:
        name: Update iptables rules
        user: root
        minute: '{{ 59 | random }}'
        hour: '{{ 23 | random }}'
        job: '/root/newborn/iptables.sh >/dev/null 2>&1'

    - name: Firewall | Create a cron job to fix rules
      cron:
        name: Lookup iptables rules and fix if needed
        user: root
        minute: '*/5'
        job: '/root/newborn/iptables.sh fix >/dev/null 2>&1'

    # ┌──────────┐
    # │   BASH   │
    # └──────────┘

    - name: Bash | Copy .bashrc file
      copy:
        src: configs/bash
        dest: /etc/bash.bashrc
        owner: root
        group: root
        mode: '0644'

    - name: Bash | Delete root-related .bashrc file
      file:
        path: /root/.bashrc
        state: absent

    - name: Bash | Set server name to .bashrc file
      lineinfile:
        path: /etc/bash.bashrc
        regexp: '^MYHOSTNAME=""$'
        line: 'MYHOSTNAME="{{ newborn_name }}"'

    # ┌─────────────────┐
    # │   REMOVE SNAP   │
    # └─────────────────┘

    - name: Snap | Remove all installed snaps
      script: scripts/remove_snap.sh
      when: newborn_remove_snap == "y"

    - name: Snap | Check if snap-related systemd unit files exist
      stat:
        path: "/lib/systemd/system/{{ item.file_name }}"
      when: newborn_remove_snap == "y"
      register: snap_unit_stats
      loop_control:
        label: "{{ item.name }}"
      loop:
        - name: snapd
          file_name: snapd.service
        - name: snapd.socket
          file_name: snapd.socket

    - name: Snap | Stop snap services
      service:
        name: "{{ item.item.name }}"
        state: stopped
        enabled: false
      when:
        - newborn_remove_snap == "y"
        - item.stat.exists
      loop_control:
        label: "{{ item.item.name }}"
      loop: "{{ snap_unit_stats.results }}"

    - name: Snap | Remove snap package
      apt:
        name: snapd
        state: absent
        purge: yes
        autoremove: yes
        update_cache: yes
      when: newborn_remove_snap == "y"

    - name: Snap | Clean up snap data
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/cache/snapd
        - "{{ ansible_env.HOME }}/snap"
      when: newborn_remove_snap == "y"

    # ┌────────────┐
    # │   DOCKER   │
    # └────────────┘

    - name: Docker | Add repository key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
      when: newborn_oci_runtime == "docker"

    - name: Docker | Add repository
      apt_repository:
        repo: "deb [arch={{ newborn_arch.stdout }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        update_cache: yes
      when: newborn_oci_runtime == "docker"

    - name: Docker | Install
      apt:
        name: docker-ce
        lock_timeout: 600
      when: newborn_oci_runtime == "docker"

    - name: Docker | Copy config file
      copy:
        src: configs/docker-daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0644'
      when: newborn_oci_runtime == "docker"

    - name: Docker | Restart daemon
      service:
        name: docker
        state: restarted
      when: newborn_oci_runtime == "docker"

    - name: Docker | Create plugins directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
      when: newborn_oci_runtime == "docker" and newborn_oci_compose == "y"

    - name: Docker | Install Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v5.0.2/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
      when: newborn_oci_runtime == "docker" and newborn_oci_compose == "y"

    # ┌────────────┐
    # │   PODMAN   │
    # └────────────┘

    - name: Podman | Install
      apt:
        name: podman
        lock_timeout: 600
      when: newborn_oci_runtime == "podman"

    - name: Podman | Install Compose
      apt:
        name: podman-compose
      when: newborn_oci_runtime == "podman" and newborn_oci_compose == "y"

    # ┌─────────┐
    # │   K0S   │
    # └─────────┘

    - name: k0s | Download installer
      get_url:
        url: https://get.k0s.sh
        dest: /tmp/k0s-install.sh
        mode: '0755'
      when: newborn_k8s_runtime == "k0s"

    - name: k0s | Execute installer
      command: /tmp/k0s-install.sh
      when: newborn_k8s_runtime == "k0s"

    - name: k0s | Remove installer
      file:
        path: /tmp/k0s-install.sh
        state: absent
      when: newborn_k8s_runtime == "k0s"

    - name: k0s | Create config directory
      file:
        path: /etc/k0s
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: newborn_k8s_runtime == "k0s"

    - name: k0s | Create config file
      shell: k0s config create > /etc/k0s/k0s.yaml
      when: newborn_k8s_runtime == "k0s"

    # > sudo k0s install controller --config /etc/k0s/k0s.yaml --enable-worker --kubelet-extra-args="--node-ip=10.92.0.2 --address=10.92.0.2" --start
    # > sudo k0s kubeconfig admin > ~/.kube/config
    # > kubectl get nodes -o wide -w
    # > sudo k0s token create --role=worker
    #
    # on worker:
    # > sudo k0s install worker --token-file .token --kubelet-extra-args="--node-ip=10.92.0.3 --address=10.92.0.3" --start

    # ┌──────────────┐
    # │   MICROK8S   │
    # └──────────────┘

    - name: Microk8s | Install Snap
      apt:
        name:
          - snapd
        lock_timeout: 600
      when: newborn_k8s_runtime == "microk8s"

    - name: Microk8s | Install MicroK8S
      shell: snap install microk8s --classic
      when: newborn_k8s_runtime == "microk8s"

    # ┌──────────┐
    # │   USER   │
    # └──────────┘

    - name: User | Create user
      user:
        name: "{{ newborn_user }}"
        password: "{{ newborn_password | password_hash('sha512', newborn_password_salt) }}"
        shell: /bin/bash

    - name: User | Add user to group "sudo"
      user:
        name: "{{ newborn_user }}"
        groups: sudo
        append: true

    - name: User | Add user to group "docker"
      user:
        name: "{{ newborn_user }}"
        groups: docker
        append: true
      when: newborn_oci_runtime == "docker"

    - name: User | Create directory ~/.kube
      file:
        path: "/home/{{ newborn_user }}/.kube"
        state: directory
        owner: "{{ newborn_user }}"
        group: "{{ newborn_user }}"
        mode: '0755'
      when: newborn_k8s_runtime == "k0s"

    - name: User/k0s | Create file ~/.kube/config
      file:
        path: "/home/{{ newborn_user }}/.kube/config"
        state: touch
        owner: "{{ newborn_user }}"
        group: "{{ newborn_user }}"
        mode: '0600'
      when: newborn_k8s_runtime == "k0s"

    - name: User/k0s] [Add kubectl alias to .bashrc
      lineinfile:
        path: /etc/bash.bashrc
        line: alias kubectl='k0s kubectl --kubeconfig=$HOME/.kube/config'
        create: yes
      when: newborn_k8s_runtime == "k0s"

    - name: User/Microk8s | Add user to group "microk8s"
      user:
        name: "{{ newborn_user }}"
        groups: microk8s
        append: true
      when: newborn_k8s_runtime == "microk8s"

    - name: User | Remove .bashrc file
      file:
        path: "/home/{{ newborn_user }}/.bashrc"
        state: absent

    - name: User | Create .ssh directory
      file:
        path: "/home/{{ newborn_user }}/.ssh"
        state: directory
        owner: "{{ newborn_user }}"
        group: "{{ newborn_user }}"

    - name: User | Add SSH authorized key
      lineinfile:
        path: "/home/{{ newborn_user }}/.ssh/authorized_keys"
        line: "{{ newborn_ssh_key_public }}"
        create: yes
        owner: "{{ newborn_user }}"
        group: "{{ newborn_user }}"
        mode: '0644'

    # ┌────────────────────┐
    # │   OPENSSH SERVER   │
    # └────────────────────┘

    - name: OpenSSH | Set server config
      copy:
        src: configs/sshd
        dest: /etc/ssh/sshd_config
        mode: '0644'

    - name: OpenSSH | Set SSH port to config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^Port '
        line: "Port {{ newborn_ssh_port }}"

    - name: OpenSSH | Restart server
      systemd_service:
        name: ssh
        state: restarted
        daemon_reload: true

    - name: OpenSSH | Execute the iptables script to reflect changes in SSH port
      shell: /root/newborn/iptables.sh
